function parseGrade(id){const el=document.getElementById(id);const raw=el.value;if(!raw||raw.trim()==="")return NaN;const v=parseFloat(raw.toString().replace(',','.'));if(!isFinite(v))return NaN;return v}
function showError(id,msg){document.getElementById('err-'+id).textContent=msg||'';const input=document.getElementById(id);if(msg){input.setAttribute('aria-invalid','true')}else{input.removeAttribute('aria-invalid')}}
function clearErrors(){['grade1','grade2','grade3'].forEach(id=>showError(id,''))}
function formatNumber(n){return Number(n).toFixed(2)}
const R=70;const CIRC=2*Math.PI*R;function drawCircleProgress(percent){const circle=document.querySelector('#resultCard circle.progress');const clamped=Math.max(0,Math.min(100,percent));const offset=CIRC*(1-(clamped/100));if(circle){circle.style.strokeDasharray=CIRC.toFixed(2);circle.style.strokeDashoffset=offset.toFixed(2)}}
function validateGrades(g1,g2,g3){clearErrors();let ok=!0;if(!isFinite(g1)||g1<0||g1>100){showError('grade1','الرجاء إدخال معدل صحيح بين 0 و 100');ok=!1}
if(!isFinite(g2)||g2<0||g2>100){showError('grade2','الرجاء إدخال معدل صحيح بين 0 و 100');ok=!1}
if(!isFinite(g3)||g3<0||g3>100){showError('grade3','الرجاء إدخال معدل صحيح بين 0 و 100');ok=!1}
return ok}
function calculateAndShow(){const g1=parseGrade('grade1');const g2=parseGrade('grade2');const g3=parseGrade('grade3');if(!validateGrades(g1,g2,g3))return;const w1=0.20,w2=0.40,w3=0.40;const d1=g1*w1;const d2=g2*w2;const d3=g3*w3;const result=d1+d2+d3;document.getElementById('average-result').textContent=formatNumber(result)+'%';const tbody=document.getElementById('resultTableBody');tbody.innerHTML='';const rows=[['أول ثانوي',g1,'20%',d1],['ثاني ثانوي',g2,'40%',d2],['ثالث ثانوي',g3,'40%',d3]];rows.forEach(r=>{const tr=document.createElement('tr');tr.innerHTML=`<td>${r[0]}</td><td>${formatNumber(r[1])}</td><td>${r[2]}</td><td>${formatNumber(r[3])}</td>`;tbody.appendChild(tr)});document.getElementById('inputCard').style.display='none';document.getElementById('resultCard').style.display='block';drawCircleProgress(result)}
document.getElementById('calculateGpaBtn').addEventListener('click',calculateAndShow);document.getElementById('clearBtn').addEventListener('click',()=>{document.getElementById('grade1').value='';document.getElementById('grade2').value='';document.getElementById('grade3').value='';clearErrors()});document.getElementById('backBtn').addEventListener('click',()=>{document.getElementById('resultCard').style.display='none';document.getElementById('inputCard').style.display='block';drawCircleProgress(0)});['grade1','grade2','grade3'].forEach(id=>{document.getElementById(id).addEventListener('keydown',(e)=>{if(e.key==='Enter')calculateAndShow();});document.getElementById(id).addEventListener('input',()=>{const v=parseGrade(id);if(isFinite(v)&&(v<0||v>100))showError(id,'الرقم خارج النطاق (0 - 100)');else showError(id,'')})});drawCircleProgress(0)